### ISSUE TITLE
ZZ_CMAP_PACKED 怎么理解

### ISSUE THREAD

**Issue by lozn00** [luoyesiqiu/simpleC#5]
ZZ_CMAP_PACKED 
我的js版本不支持，我想改正。

**Comment by luoyesiqiu** [comment]
这是jflex生成的，不需要理解

**Comment by lozn00** [comment]
是这样的，我要用来 支持js高亮，从网上找了一份出现问题。

**Comment by luoyesiqiu** [comment]
那你也可以用jflex生成一份，另外你可以看我的simpleJs项目
