### ISSUE TITLE
运行时报错了

### ISSUE THREAD

**Issue by jec1key** [luoyesiqiu/simpleC#6]
simpleC-master\libtermexec\src\main\jni\process.cpp:204:19: error: cannot initialize a parameter of type 'const char16_t *' with an lvalue of type 'const jchar *' (aka 'const unsigned short *')
simpleC-master\libtermexec\src\main\jni\process.cpp:44:30: note: passing argument to parameter 'o' here
什么原因啊？

**Comment by luoyesiqiu** [comment]
请使用其他类型代替
